name: release-follow-up
author: siegerts
description: Follow up on referenced issues and PRs after a release is published
branding:
  color: blue
  icon: code
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: true
  dry-run:
    description: Log proposed updates against referenced items instead of modifying resources
    default: false

runs:
  using: "node12"
  main: "dist/index.js"
