name: release-follow-up
on:
  release:
    types: [published]

jobs:
  dry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true

  prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
